# Generated by Django 4.1.3 on 2023-04-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_options_rename_message_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_name',
            new_name='user',
        ),
    ]
